"use strict";
exports.__esModule = true;
var MallardDuck_1 = require("./MallardDuck");
var FlyBehaviours_1 = require("./FlyBehaviours");
var mallardDuck = new MallardDuck_1.MallardDuck();
console.log("----INITIAL FLY BEHAVIOUR-----");
mallardDuck.performFly();
console.log("----FLY BEHAVIOUR AFTER RUNNING SETTER-----");
mallardDuck.flyBehaviourSetter(new FlyBehaviours_1.SmoothFly());
mallardDuck.performFly();
mallardDuck.performQuack();
