"use strict";
exports.__esModule = true;
var WeatherData_1 = require("./WeatherData");
var CurrentConditionsDisplay_1 = require("./CurrentConditionsDisplay");
var StatisticsDisplay_1 = require("./StatisticsDisplay");
var weatherData = new WeatherData_1.WeatherData();
var currentConditionsDisplay = new CurrentConditionsDisplay_1.CurrentConditionsDisplay(weatherData);
var statisticsDisplay = new StatisticsDisplay_1.StatisticsDisplay(weatherData);
weatherData.setMeasurements(42, 72, 108);
weatherData.setMeasurements(46, 70, 100);
weatherData.setMeasurements(40, 70, 102);
